#!/usr/bin/env python3
import yaml
import json
from sys import path
from mumc_modules.mumc_versions import get_script_version
from mumc_modules.mumc_output import get_current_directory


def libConvertToYAML(user_wl_libs,user_bl_libs):
    user_data_list=[]
    user_wl_data_list=[]
    user_bl_data_list=[]
    user_wl_data_dict={}
    user_bl_data_dict={}
    user_lib_dict={}
    user_wl_libs_loaded=json.loads(user_wl_libs)
    user_bl_libs_loaded=json.loads(user_bl_libs)

    for wlentry in user_wl_libs_loaded:
        user_wl_data_dict['user_id']=wlentry['userid']
        user_wl_data_dict['user_name']=wlentry['username']
        user_wl_data_dict['whitelist']=[]
        one_or_more_wl_entry=False
        for entry_data in wlentry:
            if (entry_data.isnumeric()):
                user_lib_dict['libid']=wlentry[entry_data]['libid']
                user_lib_dict['collectiontype']=wlentry[entry_data]['collectiontype']
                user_lib_dict['path']=wlentry[entry_data]['path']
                user_lib_dict['networkpath']=wlentry[entry_data]['networkpath']
                user_lib_dict['selection']=int(entry_data)
                user_wl_data_dict['whitelist'].append(user_lib_dict.copy())
                one_or_more_wl_entry=True
        #if user has no whitelist entries then set template with None/null values
        if (one_or_more_wl_entry == False):
            user_lib_dict['libid']=''
            user_lib_dict['collectiontype']=''
            user_lib_dict['path']=''
            user_lib_dict['networkpath']=''
            user_lib_dict['selection']=-1
            user_wl_data_dict['whitelist'].append(user_lib_dict.copy())
        user_wl_data_list.append(user_wl_data_dict.copy())

    for blentry in user_bl_libs_loaded:
        user_bl_data_dict['user_id']=blentry['userid']
        user_bl_data_dict['user_name']=blentry['username']
        user_bl_data_dict['blacklist']=[]
        one_or_more_bl_entry=False
        for entry_data in blentry:
            if (entry_data.isnumeric()):
                user_lib_dict['libid']=blentry[entry_data]['libid']
                user_lib_dict['collectiontype']=blentry[entry_data]['collectiontype']
                user_lib_dict['path']=blentry[entry_data]['path']
                user_lib_dict['networkpath']=blentry[entry_data]['networkpath']
                user_lib_dict['selection']=int(entry_data)
                user_bl_data_dict['blacklist'].append(user_lib_dict.copy())
                one_or_more_bl_entry=True
        #if user has no blacklist entries then set template with None/null values
        if (one_or_more_bl_entry == False):
            user_lib_dict['libid']=''
            user_lib_dict['collectiontype']=''
            user_lib_dict['path']=''
            user_lib_dict['networkpath']=''
            user_lib_dict['selection']=-1
            user_bl_data_dict['blacklist'].append(user_lib_dict.copy())
        user_bl_data_list.append(user_bl_data_dict.copy())

    #user_data_list=user_wl_data_list+user_bl_data_list
    for user in user_wl_data_list:
        user_data_list.append(user)
        user_data_list[user_data_list.index(user)]['blacklist']=user_bl_data_list[user_data_list.index(user)]['blacklist']

    return user_data_list


def yaml_configurationBuilder(the_dict):
    config_data={}
    config_data['version']=get_script_version()
    config_data['basic_settings']={}
    config_data['basic_settings']['filter_statements']={}
    config_data['basic_settings']['filter_statements']['movie']={}
    config_data['basic_settings']['filter_statements']['movie']['played']={}
    config_data['basic_settings']['filter_statements']['movie']['played']['condition_days']=-1
    config_data['basic_settings']['filter_statements']['movie']['played']['count_equality']='>='
    config_data['basic_settings']['filter_statements']['movie']['played']['count']=1
    config_data['basic_settings']['filter_statements']['movie']['created']={}
    config_data['basic_settings']['filter_statements']['movie']['created']['condition_days']=-1
    config_data['basic_settings']['filter_statements']['movie']['created']['count_equality']='>='
    config_data['basic_settings']['filter_statements']['movie']['created']['count']=1
    config_data['basic_settings']['filter_statements']['movie']['created']['behavioral_control']=True
    config_data['basic_settings']['filter_statements']['episode']={}
    config_data['basic_settings']['filter_statements']['episode']['played']={}
    config_data['basic_settings']['filter_statements']['episode']['played']['condition_days']=-1
    config_data['basic_settings']['filter_statements']['episode']['played']['count_equality']='>='
    config_data['basic_settings']['filter_statements']['episode']['played']['count']=1
    config_data['basic_settings']['filter_statements']['episode']['created']={}
    config_data['basic_settings']['filter_statements']['episode']['created']['condition_days']=-1
    config_data['basic_settings']['filter_statements']['episode']['created']['count_equality']='>='
    config_data['basic_settings']['filter_statements']['episode']['created']['count']=1
    config_data['basic_settings']['filter_statements']['episode']['created']['behavioral_control']=True
    config_data['basic_settings']['filter_statements']['audio']={}
    config_data['basic_settings']['filter_statements']['audio']['played']={}
    config_data['basic_settings']['filter_statements']['audio']['played']['condition_days']=-1
    config_data['basic_settings']['filter_statements']['audio']['played']['count_equality']='>='
    config_data['basic_settings']['filter_statements']['audio']['played']['count']=1
    config_data['basic_settings']['filter_statements']['audio']['created']={}
    config_data['basic_settings']['filter_statements']['audio']['created']['condition_days']=-1
    config_data['basic_settings']['filter_statements']['audio']['created']['count_equality']='>='
    config_data['basic_settings']['filter_statements']['audio']['created']['count']=1
    config_data['basic_settings']['filter_statements']['audio']['created']['behavioral_control']=True
    if (the_dict['server_brand'] == 'jellyfin'):
        config_data['basic_settings']['filter_statements']['audiobook']={}
        config_data['basic_settings']['filter_statements']['audiobook']['played']={}
        config_data['basic_settings']['filter_statements']['audiobook']['played']['condition_days']=-1
        config_data['basic_settings']['filter_statements']['audiobook']['played']['count_equality']='>='
        config_data['basic_settings']['filter_statements']['audiobook']['played']['count']=1
        config_data['basic_settings']['filter_statements']['audiobook']['created']={}
        config_data['basic_settings']['filter_statements']['audiobook']['created']['condition_days']=-1
        config_data['basic_settings']['filter_statements']['audiobook']['created']['count_equality']='>='
        config_data['basic_settings']['filter_statements']['audiobook']['created']['count']=1
        config_data['basic_settings']['filter_statements']['audiobook']['created']['behavioral_control']=True
    config_data['advanced_settings']={}
    config_data['advanced_settings']['behavioral_statements']={}
    config_data['advanced_settings']['behavioral_statements']['movie']={}
    config_data['advanced_settings']['behavioral_statements']['movie']['favorited']={}
    config_data['advanced_settings']['behavioral_statements']['movie']['favorited']['action']='keep'
    config_data['advanced_settings']['behavioral_statements']['movie']['favorited']['user_conditional']='any'
    config_data['advanced_settings']['behavioral_statements']['movie']['favorited']['played_conditional']='ignore'
    config_data['advanced_settings']['behavioral_statements']['movie']['favorited']['action_control']=3
    config_data['advanced_settings']['behavioral_statements']['movie']['favorited']['advanced']={}
    config_data['advanced_settings']['behavioral_statements']['movie']['favorited']['advanced']['genre']=0
    config_data['advanced_settings']['behavioral_statements']['movie']['favorited']['advanced']['library_genre']=0
    config_data['advanced_settings']['behavioral_statements']['movie']['whitetagged']={}
    config_data['advanced_settings']['behavioral_statements']['movie']['whitetagged']['action']='keep'
    config_data['advanced_settings']['behavioral_statements']['movie']['whitetagged']['user_conditional']='all'
    config_data['advanced_settings']['behavioral_statements']['movie']['whitetagged']['played_conditional']='ignore'
    config_data['advanced_settings']['behavioral_statements']['movie']['whitetagged']['action_control']=0
    config_data['advanced_settings']['behavioral_statements']['movie']['whitetagged']['tags']=[]
    #config_data['advanced_settings']['behavioral_statements']['movie']['whitetagged']['tags'].append(None)
    config_data['advanced_settings']['behavioral_statements']['movie']['blacktagged']={}
    config_data['advanced_settings']['behavioral_statements']['movie']['blacktagged']['action']='delete'
    config_data['advanced_settings']['behavioral_statements']['movie']['blacktagged']['user_conditional']='all'
    config_data['advanced_settings']['behavioral_statements']['movie']['blacktagged']['played_conditional']='any_played'
    config_data['advanced_settings']['behavioral_statements']['movie']['blacktagged']['action_control']=0
    config_data['advanced_settings']['behavioral_statements']['movie']['blacktagged']['tags']=[]
    #config_data['advanced_settings']['behavioral_statements']['movie']['blacktagged']['tags'].append(None)
    config_data['advanced_settings']['behavioral_statements']['movie']['whitelisted']={}
    config_data['advanced_settings']['behavioral_statements']['movie']['whitelisted']['action']='keep'
    config_data['advanced_settings']['behavioral_statements']['movie']['whitelisted']['user_conditional']='any'
    config_data['advanced_settings']['behavioral_statements']['movie']['whitelisted']['played_conditional']='ignore'
    config_data['advanced_settings']['behavioral_statements']['movie']['whitelisted']['action_control']=3
    config_data['advanced_settings']['behavioral_statements']['movie']['blacklisted']={}
    config_data['advanced_settings']['behavioral_statements']['movie']['blacklisted']['action']='delete'
    config_data['advanced_settings']['behavioral_statements']['movie']['blacklisted']['user_conditional']='any'
    config_data['advanced_settings']['behavioral_statements']['movie']['blacklisted']['played_conditional']='any_played'
    config_data['advanced_settings']['behavioral_statements']['movie']['blacklisted']['action_control']=3
    config_data['advanced_settings']['behavioral_statements']['episode']={}
    config_data['advanced_settings']['behavioral_statements']['episode']['favorited']={}
    config_data['advanced_settings']['behavioral_statements']['episode']['favorited']['action']='keep'
    config_data['advanced_settings']['behavioral_statements']['episode']['favorited']['user_conditional']='any'
    config_data['advanced_settings']['behavioral_statements']['episode']['favorited']['played_conditional']='ignore'
    config_data['advanced_settings']['behavioral_statements']['episode']['favorited']['action_control']=3
    config_data['advanced_settings']['behavioral_statements']['episode']['favorited']['advanced']={}
    config_data['advanced_settings']['behavioral_statements']['episode']['favorited']['advanced']['genre']=0
    config_data['advanced_settings']['behavioral_statements']['episode']['favorited']['advanced']['season_genre']=0
    config_data['advanced_settings']['behavioral_statements']['episode']['favorited']['advanced']['series_genre']=0
    config_data['advanced_settings']['behavioral_statements']['episode']['favorited']['advanced']['library_genre']=0
    config_data['advanced_settings']['behavioral_statements']['episode']['favorited']['advanced']['studio_network']=0
    config_data['advanced_settings']['behavioral_statements']['episode']['favorited']['advanced']['studio_network_genre']=0
    config_data['advanced_settings']['behavioral_statements']['episode']['whitetagged']={}
    config_data['advanced_settings']['behavioral_statements']['episode']['whitetagged']['action']='keep'
    config_data['advanced_settings']['behavioral_statements']['episode']['whitetagged']['user_conditional']='all'
    config_data['advanced_settings']['behavioral_statements']['episode']['whitetagged']['played_conditional']='ignore'
    config_data['advanced_settings']['behavioral_statements']['episode']['whitetagged']['action_control']=0
    config_data['advanced_settings']['behavioral_statements']['episode']['whitetagged']['tags']=[]
    #config_data['advanced_settings']['behavioral_statements']['episode']['whitetagged']['tags'].append(None)
    config_data['advanced_settings']['behavioral_statements']['episode']['blacktagged']={}
    config_data['advanced_settings']['behavioral_statements']['episode']['blacktagged']['action']='delete'
    config_data['advanced_settings']['behavioral_statements']['episode']['blacktagged']['user_conditional']='all'
    config_data['advanced_settings']['behavioral_statements']['episode']['blacktagged']['played_conditional']='any_played'
    config_data['advanced_settings']['behavioral_statements']['episode']['blacktagged']['action_control']=0
    config_data['advanced_settings']['behavioral_statements']['episode']['blacktagged']['tags']=[]
    #config_data['advanced_settings']['behavioral_statements']['episode']['blacktagged']['tags'].append(None)
    config_data['advanced_settings']['behavioral_statements']['episode']['whitelisted']={}
    config_data['advanced_settings']['behavioral_statements']['episode']['whitelisted']['action']='keep'
    config_data['advanced_settings']['behavioral_statements']['episode']['whitelisted']['user_conditional']='any'
    config_data['advanced_settings']['behavioral_statements']['episode']['whitelisted']['played_conditional']='ignore'
    config_data['advanced_settings']['behavioral_statements']['episode']['whitelisted']['action_control']=3
    config_data['advanced_settings']['behavioral_statements']['episode']['blacklisted']={}
    config_data['advanced_settings']['behavioral_statements']['episode']['blacklisted']['action']='delete'
    config_data['advanced_settings']['behavioral_statements']['episode']['blacklisted']['user_conditional']='any'
    config_data['advanced_settings']['behavioral_statements']['episode']['blacklisted']['played_conditional']='any_played'
    config_data['advanced_settings']['behavioral_statements']['episode']['blacklisted']['action_control']=3
    config_data['advanced_settings']['behavioral_statements']['audio']={}
    config_data['advanced_settings']['behavioral_statements']['audio']['favorited']={}
    config_data['advanced_settings']['behavioral_statements']['audio']['favorited']['action']='keep'
    config_data['advanced_settings']['behavioral_statements']['audio']['favorited']['user_conditional']='any'
    config_data['advanced_settings']['behavioral_statements']['audio']['favorited']['played_conditional']='ignore'
    config_data['advanced_settings']['behavioral_statements']['audio']['favorited']['action_control']=3
    config_data['advanced_settings']['behavioral_statements']['audio']['favorited']['advanced']={}
    config_data['advanced_settings']['behavioral_statements']['audio']['favorited']['advanced']['genre']=0
    config_data['advanced_settings']['behavioral_statements']['audio']['favorited']['advanced']['album_genre']=0
    config_data['advanced_settings']['behavioral_statements']['audio']['favorited']['advanced']['library_genre']=0
    config_data['advanced_settings']['behavioral_statements']['audio']['favorited']['advanced']['track_artist']=0
    config_data['advanced_settings']['behavioral_statements']['audio']['favorited']['advanced']['album_artist']=0
    config_data['advanced_settings']['behavioral_statements']['audio']['whitetagged']={}
    config_data['advanced_settings']['behavioral_statements']['audio']['whitetagged']['action']='keep'
    config_data['advanced_settings']['behavioral_statements']['audio']['whitetagged']['user_conditional']='all'
    config_data['advanced_settings']['behavioral_statements']['audio']['whitetagged']['played_conditional']='ignore'
    config_data['advanced_settings']['behavioral_statements']['audio']['whitetagged']['action_control']=0
    config_data['advanced_settings']['behavioral_statements']['audio']['whitetagged']['tags']=[]
    #config_data['advanced_settings']['behavioral_statements']['audio']['whitetagged']['tags'].append(None)
    config_data['advanced_settings']['behavioral_statements']['audio']['blacktagged']={}
    config_data['advanced_settings']['behavioral_statements']['audio']['blacktagged']['action']='delete'
    config_data['advanced_settings']['behavioral_statements']['audio']['blacktagged']['user_conditional']='all'
    config_data['advanced_settings']['behavioral_statements']['audio']['blacktagged']['played_conditional']='any_played'
    config_data['advanced_settings']['behavioral_statements']['audio']['blacktagged']['action_control']=0
    config_data['advanced_settings']['behavioral_statements']['audio']['blacktagged']['tags']=[]
    #config_data['advanced_settings']['behavioral_statements']['audio']['blacktagged']['tags'].append(None)
    config_data['advanced_settings']['behavioral_statements']['audio']['whitelisted']={}
    config_data['advanced_settings']['behavioral_statements']['audio']['whitelisted']['action']='keep'
    config_data['advanced_settings']['behavioral_statements']['audio']['whitelisted']['user_conditional']='any'
    config_data['advanced_settings']['behavioral_statements']['audio']['whitelisted']['played_conditional']='ignore'
    config_data['advanced_settings']['behavioral_statements']['audio']['whitelisted']['action_control']=3
    config_data['advanced_settings']['behavioral_statements']['audio']['blacklisted']={}
    config_data['advanced_settings']['behavioral_statements']['audio']['blacklisted']['action']='delete'
    config_data['advanced_settings']['behavioral_statements']['audio']['blacklisted']['user_conditional']='any'
    config_data['advanced_settings']['behavioral_statements']['audio']['blacklisted']['played_conditional']='any_played'
    config_data['advanced_settings']['behavioral_statements']['audio']['blacklisted']['action_control']=3
    if (the_dict['server_brand'] == 'jellyfin'):
        config_data['advanced_settings']['behavioral_statements']['audiobook']={}
        config_data['advanced_settings']['behavioral_statements']['audiobook']['favorited']={}
        config_data['advanced_settings']['behavioral_statements']['audiobook']['favorited']['action']='keep'
        config_data['advanced_settings']['behavioral_statements']['audiobook']['favorited']['user_conditional']='any'
        config_data['advanced_settings']['behavioral_statements']['audiobook']['favorited']['played_conditional']='ignore'
        config_data['advanced_settings']['behavioral_statements']['audiobook']['favorited']['action_control']=3
        config_data['advanced_settings']['behavioral_statements']['audiobook']['favorited']['advanced']={}
        config_data['advanced_settings']['behavioral_statements']['audiobook']['favorited']['advanced']['genre']=0
        config_data['advanced_settings']['behavioral_statements']['audiobook']['favorited']['advanced']['audiobook_genre']=0
        config_data['advanced_settings']['behavioral_statements']['audiobook']['favorited']['advanced']['library_genre']=0
        config_data['advanced_settings']['behavioral_statements']['audiobook']['favorited']['advanced']['track_author']=0
        config_data['advanced_settings']['behavioral_statements']['audiobook']['favorited']['advanced']['author']=0
        config_data['advanced_settings']['behavioral_statements']['audiobook']['favorited']['advanced']['library_author']=0
        config_data['advanced_settings']['behavioral_statements']['audiobook']['whitetagged']={}
        config_data['advanced_settings']['behavioral_statements']['audiobook']['whitetagged']['action']='keep'
        config_data['advanced_settings']['behavioral_statements']['audiobook']['whitetagged']['user_conditional']='all'
        config_data['advanced_settings']['behavioral_statements']['audiobook']['whitetagged']['played_conditional']='ignore'
        config_data['advanced_settings']['behavioral_statements']['audiobook']['whitetagged']['action_control']=0
        config_data['advanced_settings']['behavioral_statements']['audiobook']['whitetagged']['tags']=[]
        #config_data['advanced_settings']['behavioral_statements']['audiobook']['whitetagged']['tags'].append(None)
        config_data['advanced_settings']['behavioral_statements']['audiobook']['blacktagged']={}
        config_data['advanced_settings']['behavioral_statements']['audiobook']['blacktagged']['action']='delete'
        config_data['advanced_settings']['behavioral_statements']['audiobook']['blacktagged']['user_conditional']='all'
        config_data['advanced_settings']['behavioral_statements']['audiobook']['blacktagged']['played_conditional']='any_played'
        config_data['advanced_settings']['behavioral_statements']['audiobook']['blacktagged']['action_control']=0
        config_data['advanced_settings']['behavioral_statements']['audiobook']['blacktagged']['tags']=[]
        #config_data['advanced_settings']['behavioral_statements']['audiobook']['blacktagged']['tags'].append(None)
        config_data['advanced_settings']['behavioral_statements']['audiobook']['whitelisted']={}
        config_data['advanced_settings']['behavioral_statements']['audiobook']['whitelisted']['action']='keep'
        config_data['advanced_settings']['behavioral_statements']['audiobook']['whitelisted']['user_conditional']='any'
        config_data['advanced_settings']['behavioral_statements']['audiobook']['whitelisted']['played_conditional']='ignore'
        config_data['advanced_settings']['behavioral_statements']['audiobook']['whitelisted']['action_control']=3
        config_data['advanced_settings']['behavioral_statements']['audiobook']['blacklisted']={}
        config_data['advanced_settings']['behavioral_statements']['audiobook']['blacklisted']['action']='delete'
        config_data['advanced_settings']['behavioral_statements']['audiobook']['blacklisted']['user_conditional']='any'
        config_data['advanced_settings']['behavioral_statements']['audiobook']['blacklisted']['played_conditional']='any_played'
        config_data['advanced_settings']['behavioral_statements']['audiobook']['blacklisted']['action_control']=3
    config_data['advanced_settings']['whitetags']=[]
    config_data['advanced_settings']['blacktags']=[]
    config_data['advanced_settings']['episode_control']={}
    config_data['advanced_settings']['episode_control']['minimum_episodes']=0
    config_data['advanced_settings']['episode_control']['minimum_played_episodes']=0
    config_data['advanced_settings']['episode_control']['minimum_episodes_behavior']='Max Played Min Unplayed'
    config_data['advanced_settings']['trakt_fix']={}
    config_data['advanced_settings']['trakt_fix']['set_missing_last_played_date']={}
    config_data['advanced_settings']['trakt_fix']['set_missing_last_played_date']['movie']=True
    config_data['advanced_settings']['trakt_fix']['set_missing_last_played_date']['episode']=True
    config_data['advanced_settings']['trakt_fix']['set_missing_last_played_date']['audio']=True
    if (the_dict['server_brand'] == 'jellyfin'):
        config_data['advanced_settings']['trakt_fix']['set_missing_last_played_date']['audiobook']=True
    #config_data['advanced_settings']['console_controls']={}
    config_data['advanced_settings']['console_controls']={}
    config_data['advanced_settings']['console_controls']['headers']={}
    config_data['advanced_settings']['console_controls']['headers']['script']={}
    config_data['advanced_settings']['console_controls']['headers']['script']['show']=True
    config_data['advanced_settings']['console_controls']['headers']['script']['formatting']={}
    config_data['advanced_settings']['console_controls']['headers']['script']['formatting']['font']={}
    config_data['advanced_settings']['console_controls']['headers']['script']['formatting']['font']['color']=''
    config_data['advanced_settings']['console_controls']['headers']['script']['formatting']['font']['style']=''
    config_data['advanced_settings']['console_controls']['headers']['script']['formatting']['background']={}
    config_data['advanced_settings']['console_controls']['headers']['script']['formatting']['background']['color']=''
    config_data['advanced_settings']['console_controls']['headers']['user']={}
    config_data['advanced_settings']['console_controls']['headers']['user']['show']=True
    config_data['advanced_settings']['console_controls']['headers']['user']['formatting']={}
    config_data['advanced_settings']['console_controls']['headers']['user']['formatting']['font']={}
    config_data['advanced_settings']['console_controls']['headers']['user']['formatting']['font']['color']=''
    config_data['advanced_settings']['console_controls']['headers']['user']['formatting']['font']['style']=''
    config_data['advanced_settings']['console_controls']['headers']['user']['formatting']['background']={}
    config_data['advanced_settings']['console_controls']['headers']['user']['formatting']['background']['color']=''
    config_data['advanced_settings']['console_controls']['headers']['summary']={}
    config_data['advanced_settings']['console_controls']['headers']['summary']['show']=True
    config_data['advanced_settings']['console_controls']['headers']['summary']['formatting']={}
    config_data['advanced_settings']['console_controls']['headers']['summary']['formatting']['font']={}
    config_data['advanced_settings']['console_controls']['headers']['summary']['formatting']['font']['color']=''
    config_data['advanced_settings']['console_controls']['headers']['summary']['formatting']['font']['style']=''
    config_data['advanced_settings']['console_controls']['headers']['summary']['formatting']['background']={}
    config_data['advanced_settings']['console_controls']['headers']['summary']['formatting']['background']['color']=''
    config_data['advanced_settings']['console_controls']['footers']={}
    config_data['advanced_settings']['console_controls']['footers']['script']={}
    config_data['advanced_settings']['console_controls']['footers']['script']['show']=True
    config_data['advanced_settings']['console_controls']['footers']['script']['formatting']={}
    config_data['advanced_settings']['console_controls']['footers']['script']['formatting']['font']={}
    config_data['advanced_settings']['console_controls']['footers']['script']['formatting']['font']['color']=''
    config_data['advanced_settings']['console_controls']['footers']['script']['formatting']['font']['style']=''
    config_data['advanced_settings']['console_controls']['footers']['script']['formatting']['background']={}
    config_data['advanced_settings']['console_controls']['footers']['script']['formatting']['background']['color']=''
    config_data['advanced_settings']['console_controls']['warnings']={}
    config_data['advanced_settings']['console_controls']['warnings']['script']={}
    config_data['advanced_settings']['console_controls']['warnings']['script']['show']=True
    config_data['advanced_settings']['console_controls']['warnings']['script']['formatting']={}
    config_data['advanced_settings']['console_controls']['warnings']['script']['formatting']['font']={}
    config_data['advanced_settings']['console_controls']['warnings']['script']['formatting']['font']['color']=''
    config_data['advanced_settings']['console_controls']['warnings']['script']['formatting']['font']['style']=''
    config_data['advanced_settings']['console_controls']['warnings']['script']['formatting']['background']={}
    config_data['advanced_settings']['console_controls']['warnings']['script']['formatting']['background']['color']=''
    #config_data['advanced_settings']['console_controls']['movie']={}
    config_data['advanced_settings']['console_controls']['movie']={}
    config_data['advanced_settings']['console_controls']['movie']['delete']={}
    config_data['advanced_settings']['console_controls']['movie']['delete']['show']=True
    config_data['advanced_settings']['console_controls']['movie']['delete']['formatting']={}
    config_data['advanced_settings']['console_controls']['movie']['delete']['formatting']['font']={}
    config_data['advanced_settings']['console_controls']['movie']['delete']['formatting']['font']['color']=''
    config_data['advanced_settings']['console_controls']['movie']['delete']['formatting']['font']['style']=''
    config_data['advanced_settings']['console_controls']['movie']['delete']['formatting']['background']={}
    config_data['advanced_settings']['console_controls']['movie']['delete']['formatting']['background']['color']=''
    config_data['advanced_settings']['console_controls']['movie']['keep']={}
    config_data['advanced_settings']['console_controls']['movie']['keep']['show']=True
    config_data['advanced_settings']['console_controls']['movie']['keep']['formatting']={}
    config_data['advanced_settings']['console_controls']['movie']['keep']['formatting']['font']={}
    config_data['advanced_settings']['console_controls']['movie']['keep']['formatting']['font']['color']=''
    config_data['advanced_settings']['console_controls']['movie']['keep']['formatting']['font']['style']=''
    config_data['advanced_settings']['console_controls']['movie']['keep']['formatting']['background']={}
    config_data['advanced_settings']['console_controls']['movie']['keep']['formatting']['background']['color']=''
    config_data['advanced_settings']['console_controls']['movie']['post_processing']={}
    config_data['advanced_settings']['console_controls']['movie']['post_processing']['show']=True
    config_data['advanced_settings']['console_controls']['movie']['post_processing']['formatting']={}
    config_data['advanced_settings']['console_controls']['movie']['post_processing']['formatting']['font']={}
    config_data['advanced_settings']['console_controls']['movie']['post_processing']['formatting']['font']['color']=''
    config_data['advanced_settings']['console_controls']['movie']['post_processing']['formatting']['font']['style']=''
    config_data['advanced_settings']['console_controls']['movie']['post_processing']['formatting']['background']={}
    config_data['advanced_settings']['console_controls']['movie']['post_processing']['formatting']['background']['color']=''
    config_data['advanced_settings']['console_controls']['movie']['summary']={}
    config_data['advanced_settings']['console_controls']['movie']['summary']['show']=True
    config_data['advanced_settings']['console_controls']['movie']['summary']['formatting']={}
    config_data['advanced_settings']['console_controls']['movie']['summary']['formatting']['font']={}
    config_data['advanced_settings']['console_controls']['movie']['summary']['formatting']['font']['color']=''
    config_data['advanced_settings']['console_controls']['movie']['summary']['formatting']['font']['style']=''
    config_data['advanced_settings']['console_controls']['movie']['summary']['formatting']['background']={}
    config_data['advanced_settings']['console_controls']['movie']['summary']['formatting']['background']['color']=''
    #config_data['advanced_settings']['console_controls']['episode']={}
    config_data['advanced_settings']['console_controls']['episode']={}
    config_data['advanced_settings']['console_controls']['episode']['delete']={}
    config_data['advanced_settings']['console_controls']['episode']['delete']['show']=True
    config_data['advanced_settings']['console_controls']['episode']['delete']['formatting']={}
    config_data['advanced_settings']['console_controls']['episode']['delete']['formatting']['font']={}
    config_data['advanced_settings']['console_controls']['episode']['delete']['formatting']['font']['color']=''
    config_data['advanced_settings']['console_controls']['episode']['delete']['formatting']['font']['style']=''
    config_data['advanced_settings']['console_controls']['episode']['delete']['formatting']['background']={}
    config_data['advanced_settings']['console_controls']['episode']['delete']['formatting']['background']['color']=''
    config_data['advanced_settings']['console_controls']['episode']['keep']={}
    config_data['advanced_settings']['console_controls']['episode']['keep']['show']=True
    config_data['advanced_settings']['console_controls']['episode']['keep']['formatting']={}
    config_data['advanced_settings']['console_controls']['episode']['keep']['formatting']['font']={}
    config_data['advanced_settings']['console_controls']['episode']['keep']['formatting']['font']['color']=''
    config_data['advanced_settings']['console_controls']['episode']['keep']['formatting']['font']['style']=''
    config_data['advanced_settings']['console_controls']['episode']['keep']['formatting']['background']={}
    config_data['advanced_settings']['console_controls']['episode']['keep']['formatting']['background']['color']=''
    config_data['advanced_settings']['console_controls']['episode']['post_processing']={}
    config_data['advanced_settings']['console_controls']['episode']['post_processing']['show']=True
    config_data['advanced_settings']['console_controls']['episode']['post_processing']['formatting']={}
    config_data['advanced_settings']['console_controls']['episode']['post_processing']['formatting']['font']={}
    config_data['advanced_settings']['console_controls']['episode']['post_processing']['formatting']['font']['color']=''
    config_data['advanced_settings']['console_controls']['episode']['post_processing']['formatting']['font']['style']=''
    config_data['advanced_settings']['console_controls']['episode']['post_processing']['formatting']['background']={}
    config_data['advanced_settings']['console_controls']['episode']['post_processing']['formatting']['background']['color']=''
    config_data['advanced_settings']['console_controls']['episode']['summary']={}
    config_data['advanced_settings']['console_controls']['episode']['summary']['show']=True
    config_data['advanced_settings']['console_controls']['episode']['summary']['formatting']={}
    config_data['advanced_settings']['console_controls']['episode']['summary']['formatting']['font']={}
    config_data['advanced_settings']['console_controls']['episode']['summary']['formatting']['font']['color']=''
    config_data['advanced_settings']['console_controls']['episode']['summary']['formatting']['font']['style']=''
    config_data['advanced_settings']['console_controls']['episode']['summary']['formatting']['background']={}
    config_data['advanced_settings']['console_controls']['episode']['summary']['formatting']['background']['color']=''
    #config_data['advanced_settings']['console_controls']['audio']={}
    config_data['advanced_settings']['console_controls']['audio']={}
    config_data['advanced_settings']['console_controls']['audio']['delete']={}
    config_data['advanced_settings']['console_controls']['audio']['delete']['show']=True
    config_data['advanced_settings']['console_controls']['audio']['delete']['formatting']={}
    config_data['advanced_settings']['console_controls']['audio']['delete']['formatting']['font']={}
    config_data['advanced_settings']['console_controls']['audio']['delete']['formatting']['font']['color']=''
    config_data['advanced_settings']['console_controls']['audio']['delete']['formatting']['font']['style']=''
    config_data['advanced_settings']['console_controls']['audio']['delete']['formatting']['background']={}
    config_data['advanced_settings']['console_controls']['audio']['delete']['formatting']['background']['color']=''
    config_data['advanced_settings']['console_controls']['audio']['keep']={}
    config_data['advanced_settings']['console_controls']['audio']['keep']['show']=True
    config_data['advanced_settings']['console_controls']['audio']['keep']['formatting']={}
    config_data['advanced_settings']['console_controls']['audio']['keep']['formatting']['font']={}
    config_data['advanced_settings']['console_controls']['audio']['keep']['formatting']['font']['color']=''
    config_data['advanced_settings']['console_controls']['audio']['keep']['formatting']['font']['style']=''
    config_data['advanced_settings']['console_controls']['audio']['keep']['formatting']['background']={}
    config_data['advanced_settings']['console_controls']['audio']['keep']['formatting']['background']['color']=''
    config_data['advanced_settings']['console_controls']['audio']['post_processing']={}
    config_data['advanced_settings']['console_controls']['audio']['post_processing']['show']=True
    config_data['advanced_settings']['console_controls']['audio']['post_processing']['formatting']={}
    config_data['advanced_settings']['console_controls']['audio']['post_processing']['formatting']['font']={}
    config_data['advanced_settings']['console_controls']['audio']['post_processing']['formatting']['font']['color']=''
    config_data['advanced_settings']['console_controls']['audio']['post_processing']['formatting']['font']['style']=''
    config_data['advanced_settings']['console_controls']['audio']['post_processing']['formatting']['background']={}
    config_data['advanced_settings']['console_controls']['audio']['post_processing']['formatting']['background']['color']=''
    config_data['advanced_settings']['console_controls']['audio']['summary']={}
    config_data['advanced_settings']['console_controls']['audio']['summary']['show']=True
    config_data['advanced_settings']['console_controls']['audio']['summary']['formatting']={}
    config_data['advanced_settings']['console_controls']['audio']['summary']['formatting']['font']={}
    config_data['advanced_settings']['console_controls']['audio']['summary']['formatting']['font']['color']=''
    config_data['advanced_settings']['console_controls']['audio']['summary']['formatting']['font']['style']=''
    config_data['advanced_settings']['console_controls']['audio']['summary']['formatting']['background']={}
    config_data['advanced_settings']['console_controls']['audio']['summary']['formatting']['background']['color']=''
    if (the_dict['server_brand'] == 'jellyfin'):
        #config_data['advanced_settings']['console_controls']['audiobook']={}
        config_data['advanced_settings']['console_controls']['audiobook']={}
        config_data['advanced_settings']['console_controls']['audiobook']['delete']={}
        config_data['advanced_settings']['console_controls']['audiobook']['delete']['show']=True
        config_data['advanced_settings']['console_controls']['audiobook']['delete']['formatting']={}
        config_data['advanced_settings']['console_controls']['audiobook']['delete']['formatting']['font']={}
        config_data['advanced_settings']['console_controls']['audiobook']['delete']['formatting']['font']['color']=''
        config_data['advanced_settings']['console_controls']['audiobook']['delete']['formatting']['font']['style']=''
        config_data['advanced_settings']['console_controls']['audiobook']['delete']['formatting']['background']={}
        config_data['advanced_settings']['console_controls']['audiobook']['delete']['formatting']['background']['color']=''
        config_data['advanced_settings']['console_controls']['audiobook']['keep']={}
        config_data['advanced_settings']['console_controls']['audiobook']['keep']['show']=True
        config_data['advanced_settings']['console_controls']['audiobook']['keep']['formatting']={}
        config_data['advanced_settings']['console_controls']['audiobook']['keep']['formatting']['font']={}
        config_data['advanced_settings']['console_controls']['audiobook']['keep']['formatting']['font']['color']=''
        config_data['advanced_settings']['console_controls']['audiobook']['keep']['formatting']['font']['style']=''
        config_data['advanced_settings']['console_controls']['audiobook']['keep']['formatting']['background']={}
        config_data['advanced_settings']['console_controls']['audiobook']['keep']['formatting']['background']['color']=''
        config_data['advanced_settings']['console_controls']['audiobook']['post_processing']={}
        config_data['advanced_settings']['console_controls']['audiobook']['post_processing']['show']=True
        config_data['advanced_settings']['console_controls']['audiobook']['post_processing']['formatting']={}
        config_data['advanced_settings']['console_controls']['audiobook']['post_processing']['formatting']['font']={}
        config_data['advanced_settings']['console_controls']['audiobook']['post_processing']['formatting']['font']['color']=''
        config_data['advanced_settings']['console_controls']['audiobook']['post_processing']['formatting']['font']['style']=''
        config_data['advanced_settings']['console_controls']['audiobook']['post_processing']['formatting']['background']={}
        config_data['advanced_settings']['console_controls']['audiobook']['post_processing']['formatting']['background']['color']=''
        config_data['advanced_settings']['console_controls']['audiobook']['summary']={}
        config_data['advanced_settings']['console_controls']['audiobook']['summary']['show']=True
        config_data['advanced_settings']['console_controls']['audiobook']['summary']['formatting']={}
        config_data['advanced_settings']['console_controls']['audiobook']['summary']['formatting']['font']={}
        config_data['advanced_settings']['console_controls']['audiobook']['summary']['formatting']['font']['color']=''
        config_data['advanced_settings']['console_controls']['audiobook']['summary']['formatting']['font']['style']=''
        config_data['advanced_settings']['console_controls']['audiobook']['summary']['formatting']['background']={}
        config_data['advanced_settings']['console_controls']['audiobook']['summary']['formatting']['background']['color']=''
    config_data['advanced_settings']['UPDATE_CONFIG']=False
    config_data['advanced_settings']['REMOVE_FILES']=False
    config_data['admin_settings']={}
    config_data['admin_settings']['server']={}
    config_data['admin_settings']['server']['brand']=the_dict['server_brand']
    config_data['admin_settings']['server']['url']=the_dict['server_url']
    config_data['admin_settings']['server']['auth_key']=the_dict['auth_key']
    config_data['admin_settings']['behavior']={}
    config_data['admin_settings']['behavior']['list']=the_dict['library_setup_behavior']
    config_data['admin_settings']['behavior']['matching']=the_dict['library_matching_behavior']
    config_data['admin_settings']['users']=[]
    config_data['admin_settings']['users']+=libConvertToYAML(the_dict['user_wl_libs'],the_dict['user_bl_libs'])

    config_data['admin_settings']['api_controls']={}
    config_data['admin_settings']['api_controls']['attempts']=4
    config_data['admin_settings']['api_controls']['item_limit']=25
    config_data['admin_settings']['cache']={}
    config_data['admin_settings']['cache']['size']=32
    config_data['admin_settings']['cache']['fallback_behavior']='LRU'
    config_data['admin_settings']['cache']['last_accessed_time']=200
    config_data['DEBUG']=the_dict['DEBUG']

    #config_dump='\n---\n' + yaml.dump(config_data,sort_keys=False) + '...'

    #print(config_dump)

    #if (configPath == None):
        #configPath=get_current_directory()

    #Save the config file
    with open(the_dict['mumc_path'] / the_dict['config_file_name_yaml'],'w') as file:
        file.write('---\n')
        yaml.safe_dump(config_data,file,sort_keys=False)
        file.write('...')