name: "Request Help"
description: 'In need of a helping hand with MUMC'
labels:
- help wanted
body:
  - type: markdown
    attributes:
      value: Thank you for reaching out.
  - type: dropdown
    id: wiki
    attributes:
      label: "Have You Read The [Wiki](https://github.com/terrelsa13/MUMC/wiki):"
      description: Seriously, have you read it?
      multiple: false
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: textarea
    id: desired
    attributes:
      label: "Describe What You Are Trying To Accomplish:"
      description: Please use non technical terms.
    validations:
      required: true
  - type: textarea
    id: undesired
    attributes:
      label: "Describe What Is Happening:"
      description: Please use non technical terms.
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: "Any Additional Information You Think Is Useful:"
    validations:
      required: false
